output_dir: "exps/train_mvshuman"
true_gpu: "0,1,2"
gpu: [0,1,2]
random_seed: 0
auto_resume: True
master_port: "11326"
model_file: "gbinet"
model_name: "GBiNet"
dataset: "mvs_human"
max_depth: 8
find_unused_parameters: True
img_mean: [0.5, 0.5, 0.5]
img_std: [0.5, 0.5, 0.5]

model:
  is_stage: True
  stage_num: 4
  output_channels: [64, 32, 16, 8]
  group_nums: [8, 8, 8, 4]
  feat_name: "DeformStageNet"
  use_3dbn: True
  stage_info:
    scale:
      "0": 0.125
      "1": 0.25
      "2": 0.5
      "3": 1.0
    depth2stage:
      "1": 0
      "2": 0
      "3": 1
      "4": 1
      "5": 2
      "6": 2
      "7": 3
      "8": 3
      "9": 3 # needed and invalid, just for checking

scheduler:
  name: "multi_step"
  milestones: [18, 20, 22]
  gamma: 0.5
  change: True

solver:
  name: "adam"
  base_lr: 1.e-4
  weight_decay: 0.0
  betas: [0.9, 0.999]

train:
  batch_size: 3
  checkpoint_period: 1
  log_period: 10
  val_period: 1
  max_epoch: 23
  val_metric: "thres2mm_accu"

val:
  batch_size: 2
  log_period: 10
  
data:
  num_workers: 6
  out_scale: 1.0
  train:
    root_dir: '/mnt/dataset/06Visg-Azure-kinect/dataset/newmvs_human/mvs_human_1024/'
    num_view: 3
    interval_scale: 0.8
    num_depth: 256
    self_norm: False
    color_mode: null
    random_view: True
    listfile:  'mvs_views.txt'
  val:
    root_dir: '/mnt/dataset/06Visg-Azure-kinect/dataset/newmvs_human/mvs_human_1024/'
    num_view: 3
    interval_scale: 0.8
    num_depth: 256
    self_norm: False
    color_mode: null
    listfile: 'mvs_views.txt'